### ISSUE TITLE
Getting "Error: found `private` instead of statement" as a result, trying to run your code.  

### ISSUE THREAD

**Issue by CircuitCoder4696** [d-gamedev-team/dimgui#18]
For some reason, it keeps returning an error and I can't seem to get past it without removing 'private'.  Not sure what the issue is, I'm using the compiler downloaded from dlang.org (dmd), but it seems to have problems with "./glwt/signals.d".

**Comment by AndrejMitrovic** [comment]
It currently seems to work ok with 2.091.1 on Windows & Linux. Please re-open the issue if it's still a problem.

Unfortunately there's no CI system in place yet to catch these bugs. I'll add something soon.
