### ISSUE TITLE
Not sure why you commented out the entire code-block save for the beginning curly-brace.  

### ISSUE THREAD

**Issue by CircuitCoder4696** [d-gamedev-team/dimgui#19]
<img src="https://cdn.discordapp.com/attachments/644356620461277195/648437591557013504/unknown.png"/>?  You commented out one of the brackets, and I'm not sure why you commented out the entire code-block save for the beginning curly-brace.

**Comment by AndrejMitrovic** [comment]
I can't find this code fragment anymore. It looks like it may have been in the `glwtf` dependency? Anyway, please reopen if it's still an issue. Thanks.
