### ISSUE TITLE
Macbook Retina display support

### ISSUE THREAD

**Issue by SerialVelocity** [d-gamedev-team/dimgui#4]
Currently, when using a retina display, the screen looks like this:
![colors-example-bug](https://cloud.githubusercontent.com/assets/422338/3712229/2db3a9de-1505-11e4-87e8-c0a8df3ebeb1.png)

This is wrong because the retina display is actually a high-dpi display and GLFW3 handles these displays slightly differently.

If I try and fix it by applying a patch such as this:
```diff
diff --git i/examples/colors/colors.d w/examples/colors/colors.d
index 80e6a1e..7265649 100644
--- i/examples/colors/colors.d
+++ w/examples/colors/colors.d
@@ -76,7 +76,7 @@ struct GUI
 
         int width;
         int height;
-        glfwGetWindowSize(window.window, &width, &height);
+        glfwGetFramebufferSize(window.window, &width, &height);
 
         // trigger initial viewport transform.
         onWindowResize(width, height);
@@ -218,6 +218,7 @@ struct GUI
             device coordinate space to window space. It specifies the
             viewable region of a window.
         */
+        glfwGetFramebufferSize(window.window, &width, &height);
         glViewport(x, y, width, height);
 
         windowWidth = width;
```

Then I get this instead:
![colors-partial-fix](https://cloud.githubusercontent.com/assets/422338/3712244/f9854932-1505-11e4-8365-aedf345bb248.png)

The text is way too small. This problem may be related to this though:
https://github.com/AdrienHerubel/imgui/issues/3

**Comment by AndrejMitrovic** [comment]
I've added your suggested fix to `master`. Thanks!
