### ISSUE TITLE
glad-drey dependency?

### ISSUE THREAD

**Issue by taylorh140** [d-gamedev-team/dimgui#8]
the glad-drey depenency is not available? is there a workaround?

**Comment by aaronhyperum** [comment]
Is there any intent to fix this?

**Comment by dmi7ry** [comment]
Hey, any chances to fix?

**Comment by AndrejMitrovic** [comment]
Will resolve today.

**Comment by AndrejMitrovic** [comment]
I've pushed a fix to `master`. Please try it out and let me know if it works for you. The examples worked for me on Ubuntu Trusty and DMD v2.071.0.

Btw, `glwtf` and `glfw` are not available as dub projects. There is [derelict-glfw](http://code.dlang.org/packages/derelict-glfw3) of course, but I'll need to change the code to use it. As for `glwtf` I'm not sure whether there are any plans to dubify it.

**Comment by AndrejMitrovic** [comment]
Also, holy hell does Posix need 50 different libraries linked in to make glfw work.. damn. I wonder just how cross-platform listing all the `X*` libs is.

**Comment by dmi7ry** [comment]
Yes, `dimgui` compiles fine now, but examples not.

**Comment by AndrejMitrovic** [comment]
Can you list the errors please? :)

**Comment by AndrejMitrovic** [comment]
Also, what system are you running it on (and which compiler + version)

**Comment by dmi7ry** [comment]
examples - it references (dub.json) to invalid packages (`glwtf` and `glfw`, you wrote about this)

**Comment by AndrejMitrovic** [comment]
Argh, I missed that one. Fixing..

**Comment by AndrejMitrovic** [comment]
Ok so all three example projects build & run for me now.

**Comment by dmi7ry** [comment]
.dub\build\application-debug-windows-x86-dmd_2071-E57EE595C2C7444FACB2A4027035F3DF\colors.obj(colors)
     Error 42: Symbol Undefined _glfwGetWindowSize
    .dub\build\application-debug-windows-x86-dmd_2071-E57EE595C2C7444FACB2A4027035F3DF\colors.obj(colors)
     Error 42: Symbol Undefined _glfwGetMouseButton
    .dub\build\application-debug-windows-x86-dmd_2071-E57EE595C2C7444FACB2A4027035F3DF\colors.obj(colors)
     Error 42: Symbol Undefined _glfwGetCursorPos

etc
What .lib I need add for it works?

**Comment by AndrejMitrovic** [comment]
I've added an import lib to `master` and to the dub configs. You'll need the 32-bit GLFW DLL binary from http://www.glfw.org/download.html (install the VS2010 one). Put it next to the `.exe` file when running a binary.

**Comment by dmi7ry** [comment]
Thank you!
Now all compiles fine, but when I tried run, I have an error:

    glwtf.exception.WindowException@src\glwtf\window.d(119): Unable to initialize OpenGL forward compatible context (Version >= 3.0).
    ----------------
    0x0041EF89 in D5glwtf6window6Window32create_highest_available_contextMFiiAyaPS6deimos4glfw5glfw311GLFWmonitor328D3215C6E03C823F6798D9EAC66B2E at f:\projects\visual studio 2015\t\dimgui\src\glwtf\window.d(120)
    0x00413D49 in glwtf.window.Window window.createWindowContext(immutable(char)[], window.WindowMode, int, int) at f:\projects\visual studio 2015\t\dimgui\examples\colors\window.d(125)
    0x00413B4A in glwtf.window.Window window.createWindow(immutable(char)[], window.WindowMode, int, int) at f:\projects\visual studio 2015\t\dimgui\examples\colors\window.d(67)
    0x00404137 in _Dmain at f:\projects\visual studio 2015\t\dimgui\examples\colors\colors.d(260)
    0x00441DFF in D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv
    0x00441DC3 in void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll()
    0x00441CC4 in _d_run_main
    0x00413A98 in main at f:\projects\visual studio 2015\t\dimgui\examples\colors\colors.d(7)
    0x0047CE91 in mainCRTStartup
    0x7657338A in BaseThreadInitThunk
    0x770A9902 in RtlInitializeExceptionChain
    0x770A98D5 in RtlInitializeExceptionChain

As I understand, something wrong with my system?

**Comment by AndrejMitrovic** [comment]
You might have old drivers, or ones which don't support OpenGL v3.x+. I'd suggest googling around a bit. :)

In the meantime I'll have a look whether I can add support for OpenGL v2.x.

**Comment by AndrejMitrovic** [comment]
Opened separate issue for v2.x support, in the meantime I'm closing this as fixed. https://github.com/d-gamedev-team/dimgui/issues/9
